# Generated by Django 3.2.13 on 2022-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_or_domain', models.CharField(blank=True, default='127.0.0.1', max_length=20, null=True)),
                ('type', models.CharField(choices=[('match', 'Match')], default='match', max_length=10)),
                ('title', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
