# Generated by Django 3.2.13 on 2023-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('complete', 'Complete'), ('failed', 'Failed')], max_length=10, null=True)),
                ('output_path', models.TextField(blank=True, null=True)),
                ('download_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
